//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public car()
        {
            this.penalties = new HashSet<penalties>();
        }
    
        public string VIN { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> id_engine { get; set; }
        public Nullable<int> id_type_of_drive { get; set; }
        public Nullable<int> Color_num { get; set; }
        public Nullable<int> code_region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<penalties> penalties { get; set; }
        public virtual region region { get; set; }
        public virtual car_colors car_colors { get; set; }
        public virtual engine_types engine_types { get; set; }
        public virtual type_of_drive type_of_drive { get; set; }
    }
}
