//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class licence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public licence()
        {
            this.penalties = new HashSet<penalties>();
            this.category = new HashSet<category>();
        }
    
        public Nullable<System.DateTime> licence_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public string categories { get; set; }
        public string licence_series { get; set; }
        public string licence_number { get; set; }
        public Nullable<int> Id_driver { get; set; }
        public Nullable<int> id_status { get; set; }
        public int id_licence { get; set; }
    
        public virtual driver driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<penalties> penalties { get; set; }
        public virtual status_licence status_licence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> category { get; set; }
    }
}
