//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class upEntities : DbContext
    {
        private static upEntities _context;
        public upEntities()
            : base("name=upEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static upEntities GetContext() 
        {
            if (_context == null)
            _context = new upEntities();
            return _context;
        }
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<car_colors> car_colors { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<engine_types> engine_types { get; set; }
        public virtual DbSet<history_hanges_statuses> history_hanges_statuses { get; set; }
        public virtual DbSet<licence> licence { get; set; }
        public virtual DbSet<penalties> penalties { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<status_licence> status_licence { get; set; }
        public virtual DbSet<status_penalties> status_penalties { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_of_drive> type_of_drive { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<roles> roles { get; set; }
    }
}
