//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class penalties
    {
        public int id_penaltie { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> id_status_penaltie { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<int> id_licence { get; set; }
        public string VIN_car { get; set; }
        public byte[] photo_car { get; set; }
    
        public virtual car car { get; set; }
        public virtual licence licence { get; set; }
        public virtual status_penalties status_penalties { get; set; }
    }
}
